# Generated by Django 5.2.3 on 2025-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_savingstarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
