# Generated by Django 5.2.3 on 2025-07-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_loan_due_date_loan_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
